---
title: "p8105_hw1_lz2657"
author: Lingyu Zhang
date: Sep 19, 2018
output: github_document
---

```{r tidyverse, include = FALSE}
library(tidyverse)
```

# Problem 1

First, I create the required data frame:

```{r problem1_df}
set.seed(1)

problem1_df = tibble(
  vec_unif = runif(n = 10, min = 0, max = 5),
  vec_logical = vec_unif > 2,
  vec_char = c("a","b","c","d","e","f","g","h","i","j"),
  vec_factor = factor(c("right","left","right","right","left","right","right","left","right","left"))
)

problem1_df
```

Now I take the mean of each variable in the dataframe:

```{r problem1_mean, eval = FALSE}
mean(problem1_df$vec_unif)
mean(problem1_df$vec_logical)
mean(problem1_df$vec_char)
mean(problem1_df$vec_factor)
```

The means of character and factor variables don't work because they are not numerical.

Then try to convert logical, character, and factor variables to numeric:

```{r problem1_numeric, eval = FALSE}
as.numeric(problem1_df$vec_logical)
as.numeric(problem1_df$vec_char)
as.numeric(problem1_df$vec_factor)
```

We can see that logical and factor variables can be converted while the charater ones can not.